### ISSUE TITLE
Where is this rt-local-usb-bridge is define? 

### ISSUE THREAD

**Issue by knyeoh** [modular-things/modular-things#4]
Could advice where is this rt-local-usb-bridge being define?   I see it being search using:

let usbBridge = await osap.nr.find("rt-local-usb-bridge", graph)

![image](https://user-images.githubusercontent.com/121937227/212693061-b0858399-1f53-4be3-9f46-b05006a937c3.png)

Any idea?  

Thanks,
 KN

**Comment by Merlin04** [comment]
It's being defined here: https://github.com/modular-things/modular-things/blob/main/js/local/osapSerialBridge.js#L27

It's the OSAP vertex for the local serial bridge.

**Comment by knyeoh** [comment]
Seems like it does not see this vertex during execution of this command,  is there a way to list all the OSAP vertices in the graph?  Do I need to change anything in the code to run? 

osap.nr.find("rt_local-usb-bridge", graph)

Thanks, KN

**Comment by knyeoh** [comment]
I re-clone from your repo and it work, seem like the file in Jake repo is bad.

![image](https://user-images.githubusercontent.com/121937227/213419701-1f39a275-afc5-4959-aa66-12170cc6f78f.png)
